const actionTypes = Object.freeze({
	//app
	APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
	CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
	CHANGE_THEME: 'CHANGE_THEME',
	OPEN_MANAGE_BOOK_MODAL: 'OPEN_MANAGE_BOOK_MODAL',
	CLOSE_MANAGE_BOOK_MODAL: 'CLOSE_MANAGE_BOOK_MODAL',
	OPEN_CLOSE_OPTION_MENU: 'OPEN_CLOSE_OPTION_MENU',
	CLOSE_OPTION_MENU: 'CLOSE_OPTION_MENU',
	OPEN_SUB_OPTION_MENU: 'OPEN_SUB_OPTION_MENU',
	CLOSE_SUB_OPTION_MENU: 'CLOSE_SUB_OPTION_MENU',
	FETCH_REQUIRED_BOOK_DATA_START: 'FETCH_REQUIRED_BOOK_DATA_START',
	FETCH_REQUIRED_BOOK_DATA_SUCCEED: 'FETCH_REQUIRED_BOOK_DATA_SUCCEED',
	FETCH_REQUIRED_BOOK_DATA_FAILED: 'FETCH_REQUIRED_BOOK_DATA_FAILED',
	FETCH_ALL_BOOK_SUCCEED: 'FETCH_ALL_BOOK_SUCCEED',
	FETCH_ALL_BOOK_FAILED: 'FETCH_ALL_BOOK_FAILED',
	FETCH_ALL_NEW_BOOK_SUCCEED: 'FETCH_ALL_NEW_BOOK_SUCCEED',
	FETCH_ALL_NEW_BOOK_FAILED: 'FETCH_ALL_NEW_BOOK_FAILED',
	FETCH_ALL_BOOK_BY_GENRE_SUCCEED: 'FETCH_ALL_BOOK_BY_GENRE_SUCCEED',
	FETCH_ALL_BOOK_BY_GENRE_FAILED: 'FETCH_ALL_BOOK_BY_GENRE_FAILED',
	FETCH_BOOK_INFO_BY_ID_SUCCEED: 'FETCH_BOOK_INFO_BY_ID_SUCCEED',
	FETCH_BOOK_INFO_BY_ID_FAILED: 'FETCH_BOOK_INFO_BY_ID_FAILED',
	CLEAR_BOOK_INFO: 'CLEAR_BOOK_INFO',

	//user
	USER_SIGN_UP_SUCCEED: 'USER_SIGN_UP_SUCCEED',
	USER_SIGN_UP_FAILED: 'USER_SIGN_UP_FAILED',

	USER_LOGIN_SUCCEED: 'USER_LOGIN_SUCCEED',
	USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
	USER_LOGOUT: 'USER_LOGOUT',

	//admin
	ADD_NEW_BOOK_SUCCEED: 'ADD_NEW_BOOK_SUCCEED',
	ADD_NEW_BOOK_FAILED: 'ADD_NEW_BOOK_FAILED',
	UPDATE_BOOK_INFO_SUCCEED: 'UPDATE_BOOK_INFO_SUCCEED',
	UPDATE_BOOK_INFO_FAILED: 'UPDATE_BOOK_INFO_FAILED',
	DELETE_BOOK_SUCCEED: 'DELETE_BOOK_SUCCEED',
	DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',
});

export default actionTypes;
